### ISSUE TITLE
Add e2e tests to be run on actual Azure CVM

### ISSUE THREAD

**Issue by surajssd** [kinvolk/azure-cvm-tooling#8]
### Static setup using terraform (or whatever is convenient)
- Create a RG that will run the CVM tests.
- Permissions to bring up a CVM in a RG only will be given via [federated auth](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure).

## For each CI run

- Clone code and build binaries locally in the normal runners.
- Bring up a CVM, install dependencies for dynamically linked libraries.
- Copy (scp) the binaries over the the CVM.
- Run the example code and other tests. (replace the code that uses local check-in artifacts with the artifacts available on the machine)
- Clean up the CVM.

**Comment by surajssd** [comment]
- Create a RG that will run the CVM tests.
- Permissions to bring up a CVM in a RG only.
- Bring up a CVM, install dependencies like Rust.
- Clone the code, build stuff in that VM.
- Run the example code and other tests. (replace the code that uses local check-in artifacts with the artifacts available on the machine)

---

- Do we need to set up machine for each test?
- Can't we use the reuse the machine once set up using terraform or some such infra provider? We can turn it off when there are no test running for more than ten minutes. Or is it easier from maintenance and debugging pov to just have new machine bring up on each test run?
- Do we need garm here?

**Comment by mkulke** [comment]
> * Bring up a CVM, install dependencies like Rust.
> * Clone the code, build stuff in that VM.

Why build the code on the CVM? Wouldn't it be more convenient to build code locally on the GA runner and scp the bins to the host?

> * Do we need to set up machine for each test?
> * Can't we use the reuse the machine once set up using terraform or some such infra provider? We can turn it off when there are no test running for more than ten minutes. Or is it easier from maintenance and debugging pov to just have new machine bring up on each test run?

In my experience those CVMs come up pretty quickly. We could also stop and start an existing VM, but I wouldn't bother re-using a VM unless creating/discarding per test is a nuisance. 

Debugging a failed run could be covered by having an opt-out flag for the cleanup method in the workflow. But then we cannot use ephemeral ssh keys, etc etc. I'd also address that once the need arises.

> * Do we need garm here?

There is no self-hosted runner involved, so i'd say no.

**Comment by surajssd** [comment]
@mkulke updated the description.
